apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: null
  generation: 1
  labels:
    run: poc-product-service
  name: poc-product-service
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/poc-product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: poc-product-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: poc-product-service
    spec:
      containers:
      - image: repository.romcore.io/poc-product-service:0.0.1
        imagePullPolicy: IfNotPresent
        name: poc-product-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: nexus
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
